//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class BATCH
    {
        public BATCH()
        {
            this.ADMISSIONINFOes = new HashSet<ADMISSIONINFO>();
        }
    
        public int ID { get; set; }
        public int Year { get; set; }
        public string BatchNo { get; set; }
        public string BanglaBatch { get; set; }
    
        public virtual ICollection<ADMISSIONINFO> ADMISSIONINFOes { get; set; }
    }
}
