//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOK_ISSUE
    {
        public int Id { get; set; }
        public Nullable<int> StudentPKId { get; set; }
        public string StudentId { get; set; }
        public string Semester { get; set; }
        public Nullable<int> BookId { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public string BookReturnStatus { get; set; }
        public string DelayReturn { get; set; }
        public Nullable<System.DateTime> BookReturnDateFromStudent { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual ADMISSIONINFO ADMISSIONINFO { get; set; }
        public virtual BOOKS_DETAILS BOOKS_DETAILS { get; set; }
    }
}
