//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKS_DETAILS
    {
        public BOOKS_DETAILS()
        {
            this.BOOK_ISSUE = new HashSet<BOOK_ISSUE>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ProgramId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string BookName { get; set; }
        public string BookAuthor { get; set; }
        public string BookEdition { get; set; }
        public Nullable<int> PublishedYear { get; set; }
        public string SelfNumber { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<int> Quantiry { get; set; }
    
        public virtual ICollection<BOOK_ISSUE> BOOK_ISSUE { get; set; }
        public virtual SIPI_DEPARTMENT SIPI_DEPARTMENT { get; set; }
        public virtual SIPI_PROGRAM SIPI_PROGRAM { get; set; }
    }
}
