//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAMPUSINFO
    {
        public CAMPUSINFO()
        {
            this.ADMISSIONINFOes = new HashSet<ADMISSIONINFO>();
            this.ADMISSIONINFOes1 = new HashSet<ADMISSIONINFO>();
            this.ADMISSIONOFFICEs = new HashSet<ADMISSIONOFFICE>();
            this.FEESSETUPs = new HashSet<FEESSETUP>();
            this.STUDENT_ATTENDENCE = new HashSet<STUDENT_ATTENDENCE>();
            this.TEACHERs = new HashSet<TEACHER>();
        }
    
        public int Id { get; set; }
        public string CampusName { get; set; }
        public string CampusAddress { get; set; }
        public string ContactPerson { get; set; }
        public string MobileNumber { get; set; }
        public string BanglaCampus { get; set; }
    
        public virtual ICollection<ADMISSIONINFO> ADMISSIONINFOes { get; set; }
        public virtual ICollection<ADMISSIONINFO> ADMISSIONINFOes1 { get; set; }
        public virtual ICollection<ADMISSIONOFFICE> ADMISSIONOFFICEs { get; set; }
        public virtual ICollection<FEESSETUP> FEESSETUPs { get; set; }
        public virtual ICollection<STUDENT_ATTENDENCE> STUDENT_ATTENDENCE { get; set; }
        public virtual ICollection<TEACHER> TEACHERs { get; set; }
    }
}
