//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURSE_ASSIGN_TO_STUDENT
    {
        public int Id { get; set; }
        public int StudentPkId { get; set; }
        public int DepartmentId { get; set; }
        public int SemesterId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<decimal> PreStudentTheoryMarksContinuousAssessment { get; set; }
        public Nullable<decimal> PreStudentPracticalMarksContinuousAssessment { get; set; }
        public Nullable<decimal> PreStudentTheoryMarksFinalExam { get; set; }
        public Nullable<decimal> PreStudentPracticalTheoryMarksFinalExam { get; set; }
        public Nullable<decimal> TotalMarks { get; set; }
    
        public virtual ADMISSIONINFO ADMISSIONINFO { get; set; }
        public virtual COURSE COURSE { get; set; }
        public virtual SEMESTER SEMESTER { get; set; }
        public virtual SIPI_DEPARTMENT SIPI_DEPARTMENT { get; set; }
    }
}
