//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURSE_ENTRY
    {
        public COURSE_ENTRY()
        {
            this.SCHOOL_MARKS_DISTRIBUTION = new HashSet<SCHOOL_MARKS_DISTRIBUTION>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Lavle { get; set; }
        public Nullable<int> Class { get; set; }
        public string Term { get; set; }
        public string CourseName { get; set; }
        public string BanglaCourseName { get; set; }
        public string Code { get; set; }
        public Nullable<int> Marks { get; set; }
    
        public virtual SIPI_DEPARTMENT SIPI_DEPARTMENT { get; set; }
        public virtual SIPI_PROGRAM SIPI_PROGRAM { get; set; }
        public virtual ICollection<SCHOOL_MARKS_DISTRIBUTION> SCHOOL_MARKS_DISTRIBUTION { get; set; }
    }
}
