//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURSE
    {
        public COURSE()
        {
            this.COURSE_ASSIGN_TO_STUDENT = new HashSet<COURSE_ASSIGN_TO_STUDENT>();
            this.CREATE_ROUTINE = new HashSet<CREATE_ROUTINE>();
            this.CREATE_ROUTINE1 = new HashSet<CREATE_ROUTINE>();
            this.CREATE_ROUTINE2 = new HashSet<CREATE_ROUTINE>();
            this.CREATE_ROUTINE3 = new HashSet<CREATE_ROUTINE>();
            this.CREATE_ROUTINE4 = new HashSet<CREATE_ROUTINE>();
            this.CREATE_ROUTINE5 = new HashSet<CREATE_ROUTINE>();
            this.CREATE_ROUTINE6 = new HashSet<CREATE_ROUTINE>();
            this.CREATE_ROUTINE7 = new HashSet<CREATE_ROUTINE>();
            this.STUDENT_ATTENDENCE = new HashSet<STUDENT_ATTENDENCE>();
            this.STUDENT_RESULT = new HashSet<STUDENT_RESULT>();
        }
    
        public int Id { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> ProgramId { get; set; }
        public Nullable<int> SemesterId { get; set; }
        public string CourseName { get; set; }
        public string BanglaCourseName { get; set; }
        public string CourseCode { get; set; }
        public Nullable<decimal> TheoryCredit { get; set; }
        public Nullable<decimal> PracticalCredit { get; set; }
        public Nullable<decimal> TotalCredit { get; set; }
        public Nullable<decimal> TheoryMarkasContinuousAssessment { get; set; }
        public Nullable<decimal> TheoryMarkasFinalExam { get; set; }
        public Nullable<decimal> PracticalMarkasContinuousAssessment { get; set; }
        public Nullable<decimal> PracticalMarkasFinalExam { get; set; }
        public Nullable<decimal> TotalMarks { get; set; }
    
        public virtual ICollection<COURSE_ASSIGN_TO_STUDENT> COURSE_ASSIGN_TO_STUDENT { get; set; }
        public virtual SIPI_PROGRAM SIPI_PROGRAM { get; set; }
        public virtual SEMESTER SEMESTER { get; set; }
        public virtual SIPI_DEPARTMENT SIPI_DEPARTMENT { get; set; }
        public virtual ICollection<CREATE_ROUTINE> CREATE_ROUTINE { get; set; }
        public virtual ICollection<CREATE_ROUTINE> CREATE_ROUTINE1 { get; set; }
        public virtual ICollection<CREATE_ROUTINE> CREATE_ROUTINE2 { get; set; }
        public virtual ICollection<CREATE_ROUTINE> CREATE_ROUTINE3 { get; set; }
        public virtual ICollection<CREATE_ROUTINE> CREATE_ROUTINE4 { get; set; }
        public virtual ICollection<CREATE_ROUTINE> CREATE_ROUTINE5 { get; set; }
        public virtual ICollection<CREATE_ROUTINE> CREATE_ROUTINE6 { get; set; }
        public virtual ICollection<CREATE_ROUTINE> CREATE_ROUTINE7 { get; set; }
        public virtual ICollection<STUDENT_ATTENDENCE> STUDENT_ATTENDENCE { get; set; }
        public virtual ICollection<STUDENT_RESULT> STUDENT_RESULT { get; set; }
    }
}
