//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CREATE_ROUTINE
    {
        public int Id { get; set; }
        public string Day { get; set; }
        public string ClassRutinGroupId { get; set; }
        public Nullable<int> FirstClass { get; set; }
        public Nullable<int> FirstCourse { get; set; }
        public Nullable<int> FirstTeacher { get; set; }
        public Nullable<int> SecondClass { get; set; }
        public Nullable<int> SecondCourse { get; set; }
        public Nullable<int> SecondTeacher { get; set; }
        public Nullable<int> ThirdClass { get; set; }
        public Nullable<int> ThirdCourse { get; set; }
        public Nullable<int> ThirdTeacher { get; set; }
        public Nullable<int> ForthClass { get; set; }
        public Nullable<int> ForthCourse { get; set; }
        public Nullable<int> ForthTeacher { get; set; }
        public Nullable<int> FifthClass { get; set; }
        public Nullable<int> FifthCourse { get; set; }
        public Nullable<int> FifthTeacher { get; set; }
        public Nullable<int> SixthClass { get; set; }
        public Nullable<int> SixthCourse { get; set; }
        public Nullable<int> SixthTeacher { get; set; }
        public Nullable<int> SeventhClass { get; set; }
        public Nullable<int> SeventhCourse { get; set; }
        public Nullable<int> SeventhTeacher { get; set; }
        public Nullable<int> EighthClass { get; set; }
        public Nullable<int> EighthCourse { get; set; }
        public Nullable<int> EighthTeacher { get; set; }
        public string Year { get; set; }
        public Nullable<int> ProgramId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> SemesterId { get; set; }
    
        public virtual CLASSPERIOD CLASSPERIOD { get; set; }
        public virtual CLASSPERIOD CLASSPERIOD1 { get; set; }
        public virtual CLASSPERIOD CLASSPERIOD2 { get; set; }
        public virtual CLASSPERIOD CLASSPERIOD3 { get; set; }
        public virtual CLASSPERIOD CLASSPERIOD4 { get; set; }
        public virtual CLASSPERIOD CLASSPERIOD5 { get; set; }
        public virtual CLASSPERIOD CLASSPERIOD6 { get; set; }
        public virtual CLASSPERIOD CLASSPERIOD7 { get; set; }
        public virtual COURSE COURSE { get; set; }
        public virtual COURSE COURSE1 { get; set; }
        public virtual COURSE COURSE2 { get; set; }
        public virtual COURSE COURSE3 { get; set; }
        public virtual COURSE COURSE4 { get; set; }
        public virtual COURSE COURSE5 { get; set; }
        public virtual COURSE COURSE6 { get; set; }
        public virtual COURSE COURSE7 { get; set; }
        public virtual SEMESTER SEMESTER { get; set; }
        public virtual SIPI_DEPARTMENT SIPI_DEPARTMENT { get; set; }
        public virtual SIPI_PROGRAM SIPI_PROGRAM { get; set; }
        public virtual TEACHER TEACHER { get; set; }
        public virtual TEACHER TEACHER1 { get; set; }
        public virtual TEACHER TEACHER2 { get; set; }
        public virtual TEACHER TEACHER3 { get; set; }
        public virtual TEACHER TEACHER4 { get; set; }
        public virtual TEACHER TEACHER5 { get; set; }
        public virtual TEACHER TEACHER6 { get; set; }
        public virtual TEACHER TEACHER7 { get; set; }
    }
}
