//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER_EMPLOYEE_SETUP
    {
        public long ID { get; set; }
        public long ACCOUNT_ID { get; set; }
        public string NAME { get; set; }
        public string CONTACT_NO { get; set; }
        public string CONTACT_PERSON { get; set; }
        public string NATIONAL_ID { get; set; }
        public string ADDRESS { get; set; }
    
        public virtual CHART_ACCOUNT CHART_ACCOUNT { get; set; }
    }
}
