//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTMENT
    {
        public DEPARTMENT()
        {
            this.PROGRAMs = new HashSet<PROGRAM>();
            this.ROUTINEGROUPs = new HashSet<ROUTINEGROUP>();
        }
    
        public int Id { get; set; }
        public string DepartmentName { get; set; }
        public string DepartmentCode { get; set; }
        public string BanglaDepartment { get; set; }
    
        public virtual ICollection<PROGRAM> PROGRAMs { get; set; }
        public virtual ICollection<ROUTINEGROUP> ROUTINEGROUPs { get; set; }
    }
}
