//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPOSIT_PAYMENT
    {
        public long ID { get; set; }
        public long ACCOUNT_ID { get; set; }
        public Nullable<System.DateTime> DEPOSIT_PAYMENT_DATE { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<long> BANK_ACCOUNT_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public string BANK_INFO_CHEQUE { get; set; }
        public string BANK_CHEQUE { get; set; }
        public Nullable<System.DateTime> BANK_CHEQUE_DATE { get; set; }
        public Nullable<System.DateTime> CLEARING_DATE { get; set; }
        public string STATUS { get; set; }
        public string TRANSACTION_TYPE { get; set; }
        public string JOURNAL_VOUCHER { get; set; }
        public string CANCEL_JVOUCHAR { get; set; }
        public string ACCESS_BY { get; set; }
        public Nullable<System.DateTime> ACCESS_DATETIME { get; set; }
    
        public virtual CHART_ACCOUNT CHART_ACCOUNT { get; set; }
    }
}
