//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPRICIATION
    {
        public long DEP_ID { get; set; }
        public long ACCOUNT_ID { get; set; }
        public Nullable<decimal> ORIGINAL_COST { get; set; }
        public Nullable<decimal> DEP_VALUE { get; set; }
        public Nullable<decimal> NEW_ORIGINAL_COST { get; set; }
        public string ACCESS_BY { get; set; }
        public Nullable<System.DateTime> ACCESS_DATE { get; set; }
        public string JOURNAL_ID { get; set; }
    }
}
