//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPRICIATION_SETUP
    {
        public long DEP_SET_ID { get; set; }
        public long ACCOUNT_ID { get; set; }
        public Nullable<decimal> DEP_PERCENTAGE { get; set; }
        public Nullable<long> DEBIT_ACC_ID { get; set; }
        public Nullable<long> CREDIT_ACC_ID { get; set; }
        public string ACCESS_BY { get; set; }
        public Nullable<System.DateTime> ACCESS_DATE { get; set; }
    
        public virtual CHART_ACCOUNT CHART_ACCOUNT { get; set; }
    }
}
