//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISTRICT
    {
        public DISTRICT()
        {
            this.ADMISSIONINFOes = new HashSet<ADMISSIONINFO>();
            this.ADMISSIONINFOes1 = new HashSet<ADMISSIONINFO>();
            this.ADMISSIONINFOes2 = new HashSet<ADMISSIONINFO>();
            this.POSTs = new HashSet<POST>();
            this.THANAs = new HashSet<THANA>();
        }
    
        public int Id { get; set; }
        public string DistrictName { get; set; }
        public string BanglaDistrict { get; set; }
    
        public virtual ICollection<ADMISSIONINFO> ADMISSIONINFOes { get; set; }
        public virtual ICollection<ADMISSIONINFO> ADMISSIONINFOes1 { get; set; }
        public virtual ICollection<ADMISSIONINFO> ADMISSIONINFOes2 { get; set; }
        public virtual ICollection<POST> POSTs { get; set; }
        public virtual ICollection<THANA> THANAs { get; set; }
    }
}
