//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class FEES_ASSIGN_BY_CLASS
    {
        public int Id { get; set; }
        public string BnglaClassName { get; set; }
        public string ClassName { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> Year { get; set; }
        public string FeesDetailsItemName { get; set; }
        public Nullable<int> FeesDetailsId { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> Total { get; set; }
    
        public virtual FEESDETAIL FEESDETAIL { get; set; }
        public virtual SIPI_DEPARTMENT SIPI_DEPARTMENT { get; set; }
    }
}
