//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class FEESDETAIL
    {
        public FEESDETAIL()
        {
            this.FEES_ASSIGN_BY_CLASS = new HashSet<FEES_ASSIGN_BY_CLASS>();
            this.SCHOOL_FEES_COLLECTION = new HashSet<SCHOOL_FEES_COLLECTION>();
            this.STUDENTFEES = new HashSet<STUDENTFEE>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string BanglaFeesItem { get; set; }
    
        public virtual ICollection<FEES_ASSIGN_BY_CLASS> FEES_ASSIGN_BY_CLASS { get; set; }
        public virtual ICollection<SCHOOL_FEES_COLLECTION> SCHOOL_FEES_COLLECTION { get; set; }
        public virtual ICollection<STUDENTFEE> STUDENTFEES { get; set; }
    }
}
