//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class FISCAL_YEAR
    {
        public int F_YEAR_ID { get; set; }
        public string F_YEAR_NAME { get; set; }
        public System.DateTime F_YEAR_START_DATE { get; set; }
        public System.DateTime F_YEAR_END_DATE { get; set; }
        public string F_YEAR_STATUS { get; set; }
        public string ACCESS_BY { get; set; }
        public Nullable<System.DateTime> ACCESS_DATE { get; set; }
    }
}
