//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTORY_PURCHASE_ENTRY
    {
        public int Id { get; set; }
        public Nullable<int> ProductMasterEntryId { get; set; }
        public Nullable<decimal> NumberOfProduct { get; set; }
        public Nullable<decimal> SalableQuantity { get; set; }
        public Nullable<decimal> ItemPrice { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public byte[] PurchaserInfo { get; set; }
        public string SystemSerialNo { get; set; }
    }
}
