//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTORY_BRAND_NAME
    {
        public INVENTORY_BRAND_NAME()
        {
            this.INVENTORY_BRAND_CATEGORY = new HashSet<INVENTORY_BRAND_CATEGORY>();
            this.INVENTORY_PRODUCT_MASTER_ENTRY_INVENTORY = new HashSet<INVENTORY_PRODUCT_MASTER_ENTRY_INVENTORY>();
        }
    
        public int Id { get; set; }
        public string BrandName { get; set; }
        public string BrandDiscription { get; set; }
        public string ContactInfo { get; set; }
    
        public virtual ICollection<INVENTORY_BRAND_CATEGORY> INVENTORY_BRAND_CATEGORY { get; set; }
        public virtual ICollection<INVENTORY_PRODUCT_MASTER_ENTRY_INVENTORY> INVENTORY_PRODUCT_MASTER_ENTRY_INVENTORY { get; set; }
    }
}
