//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTORY_UNIT_TYPE
    {
        public INVENTORY_UNIT_TYPE()
        {
            this.INVENTORY_PRODUCT_MASTER_ENTRY_INVENTORY = new HashSet<INVENTORY_PRODUCT_MASTER_ENTRY_INVENTORY>();
        }
    
        public int Id { get; set; }
        public string UnitType { get; set; }
        public string UnitTypeDetails { get; set; }
    
        public virtual ICollection<INVENTORY_PRODUCT_MASTER_ENTRY_INVENTORY> INVENTORY_PRODUCT_MASTER_ENTRY_INVENTORY { get; set; }
    }
}
