//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTORY_PRODUCT_MASTER_ENTRY_INVENTORY
    {
        public INVENTORY_PRODUCT_MASTER_ENTRY_INVENTORY()
        {
            this.INVENTORY_PURCHAGE_DETAILS = new HashSet<INVENTORY_PURCHAGE_DETAILS>();
            this.INVENTORY_STOCK_OUT = new HashSet<INVENTORY_STOCK_OUT>();
            this.INVENTORY_STOCKOUT_DETAILS = new HashSet<INVENTORY_STOCKOUT_DETAILS>();
        }
    
        public int Id { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> UnitTypeId { get; set; }
        public string UnitTypeNote { get; set; }
        public Nullable<decimal> StockInHand { get; set; }
        public Nullable<decimal> StockPrice { get; set; }
    
        public virtual INVENTORY_BRAND_CATEGORY INVENTORY_BRAND_CATEGORY { get; set; }
        public virtual INVENTORY_BRAND_NAME INVENTORY_BRAND_NAME { get; set; }
        public virtual INVENTORY_UNIT_TYPE INVENTORY_UNIT_TYPE { get; set; }
        public virtual ICollection<INVENTORY_PURCHAGE_DETAILS> INVENTORY_PURCHAGE_DETAILS { get; set; }
        public virtual ICollection<INVENTORY_STOCK_OUT> INVENTORY_STOCK_OUT { get; set; }
        public virtual ICollection<INVENTORY_STOCKOUT_DETAILS> INVENTORY_STOCKOUT_DETAILS { get; set; }
    }
}
