//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOURNAL_VOUCHAR
    {
        public long ID { get; set; }
        public string JV_ID { get; set; }
        public long JV_ACCOUNT_ID { get; set; }
        public string JV_ACCOUNT_NAME { get; set; }
        public string JV_ACCOUNT_CODE { get; set; }
        public Nullable<decimal> JV_DEBIT_AMOUNT { get; set; }
        public Nullable<decimal> JV_CREDIT_AMOUNT { get; set; }
        public string JV_NOTES { get; set; }
        public Nullable<System.DateTime> JV_DATE { get; set; }
        public string JV_CHEQUE_NO { get; set; }
        public Nullable<System.DateTime> JV_CHEQUE_DATE { get; set; }
        public string JV_BANK_REMARK { get; set; }
        public string JV_ACCESS_BY { get; set; }
        public Nullable<System.DateTime> JV_ACCESS_DATE { get; set; }
    
        public virtual CHART_ACCOUNT CHART_ACCOUNT { get; set; }
    }
}
