//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class LMS_tblCompany
    {
        public string strCompanyID { get; set; }
        public string strCompany { get; set; }
        public string strAddress { get; set; }
        public string strIUser { get; set; }
        public string strEUser { get; set; }
        public Nullable<System.DateTime> dtIDate { get; set; }
        public Nullable<System.DateTime> dtEDate { get; set; }
    }
}
