//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEMBER_ACC_TYPE
    {
        public long TABLE_ID { get; set; }
        public long MEMBER_ACCOUNT_TYPE_ID { get; set; }
        public string ACCOUNT_PREFIX { get; set; }
    
        public virtual CHART_ACCOUNT CHART_ACCOUNT { get; set; }
    }
}
