//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEMBER_INFO
    {
        public long ID { get; set; }
        public string MEMBER_NO { get; set; }
        public string NO_OF_SHARE { get; set; }
        public string MEMBER_FULL_NAME { get; set; }
        public string FATHER_NAME { get; set; }
        public string MOTHER_NAME { get; set; }
        public string HUSBAND_NAME { get; set; }
        public string PRESENT_ADDRESS { get; set; }
        public string PERMANENT_ADDRESS { get; set; }
        public Nullable<int> MOBILE_NO { get; set; }
        public string EDUCATION_STATUS { get; set; }
        public Nullable<System.DateTime> MEMBER_BIRTH_DATE { get; set; }
        public string RELIGION { get; set; }
        public string MEMBER_OCCUPATION { get; set; }
        public string MARITAL_STATUS { get; set; }
        public string NATIONALITY { get; set; }
        public string NOMINEE_NAME { get; set; }
        public Nullable<System.DateTime> NOMINEE_BIRTH_DATE { get; set; }
        public string NOMINEE_OCCUPATION { get; set; }
        public string RELATION_WITH_NOMINEE { get; set; }
        public byte[] MEMBER_PHOTO { get; set; }
        public byte[] DIGITAL_SIGNATURE { get; set; }
        public byte[] NOMINEE_PHOTO { get; set; }
        public string ACCESS_BY { get; set; }
        public Nullable<System.DateTime> ACCESS_DATE { get; set; }
    }
}
