//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PIS_tblEmpAssignment
    {
        public System.Guid GEmpAssignID { get; set; }
        public System.Guid GEmployeeGenInfoID { get; set; }
        public Nullable<System.Guid> SectionID { get; set; }
        public Nullable<System.Guid> FloorID { get; set; }
        public Nullable<System.Guid> BlockID { get; set; }
        public Nullable<System.Guid> MachineID { get; set; }
        public Nullable<System.Guid> TableID { get; set; }
        public Nullable<System.Guid> AssetID { get; set; }
        public Nullable<System.Guid> CategoryID { get; set; }
        public Nullable<System.Guid> CategoryEmpID { get; set; }
        public Nullable<System.Guid> CategorySalaryID { get; set; }
    }
}
