//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PIS_tblEmpEducationInfo
    {
        public System.Guid GEmpEducationInfoID { get; set; }
        public System.Guid GEmployeeGenInfoID { get; set; }
        public System.Guid GEmpEduDegreeID { get; set; }
        public int intEmpEduDegreeYear { get; set; }
        public Nullable<System.Guid> GEmpEduGroupSubject { get; set; }
        public string StrEmpEduInstituteName { get; set; }
        public System.Guid GEmpEduResultID { get; set; }
        public Nullable<System.Guid> GEmpEduBoardID { get; set; }
    }
}
