//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PIS_tblEmpFamily
    {
        public System.Guid GEmpFamilyID { get; set; }
        public System.Guid GEmployeeGenInfoID { get; set; }
        public Nullable<System.Guid> GEmpFamilyType { get; set; }
        public string StrEmpFamilyMemberName { get; set; }
        public Nullable<System.DateTime> dtEmpFamilyBirthDate { get; set; }
        public int intEmpFamilyGender { get; set; }
        public System.Guid GEmpFamilyEduDegreeID { get; set; }
        public Nullable<System.Guid> GEmpFamilyProfession { get; set; }
        public Nullable<int> intEmpFamilyBloodGroup { get; set; }
        public Nullable<int> intNominee { get; set; }
        public Nullable<decimal> numShare { get; set; }
    }
}
