//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PIS_tblDistrictInfo
    {
        public System.Guid GDistrictInfoID { get; set; }
        public System.Guid GCountryNameID { get; set; }
        public string StrDistrictCode { get; set; }
        public string StrDistrictName { get; set; }
        public string StrDistrictDescription { get; set; }
    }
}
