//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PIS_tblWorkTimeScheduleSetup
    {
        public System.Guid GWorkTimeScheduleSetupID { get; set; }
        public int intWorkScheduleShift { get; set; }
        public string strWorkTimeSchedule { get; set; }
        public System.DateTime dtWorkStartTime { get; set; }
        public System.DateTime dtWorkEndTime { get; set; }
        public System.DateTime dtLunchMiddleBreakStartTime { get; set; }
        public System.DateTime dtLunchMiddleBreakEndTime { get; set; }
        public System.DateTime dtFirstTeaBreakStartTime { get; set; }
        public System.DateTime dtFirstTeaBreakEndTime { get; set; }
        public Nullable<System.DateTime> dtSecondTeaBreakStartTime { get; set; }
        public Nullable<System.DateTime> dtSecondTeaBreakEndTime { get; set; }
        public decimal numTotalWorkingHours { get; set; }
        public int intRecordStatus { get; set; }
    }
}
