//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PIS_tblGradeInfo
    {
        public System.Guid GGradeInfoID { get; set; }
        public Nullable<System.Guid> GGradeTypeID { get; set; }
        public string StrGradeName { get; set; }
        public string StrGradeDesc { get; set; }
        public decimal numMinimumSalary { get; set; }
        public decimal numMaximumSalary { get; set; }
    }
}
