//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PIS_tblEmployeeGenInfo
    {
        public System.Guid GEmployeeGenInfoID { get; set; }
        public Nullable<System.Guid> GCompanyGenInfoID { get; set; }
        public Nullable<System.Guid> GFactoryID { get; set; }
        public Nullable<System.Guid> GDesignationInfoID { get; set; }
        public Nullable<System.Guid> GLocationID { get; set; }
        public Nullable<System.Guid> GDepartmentID { get; set; }
        public Nullable<System.Guid> GEmployeeCatID { get; set; }
        public string StrEmpID { get; set; }
        public string StrEmpCardNo { get; set; }
        public string StrEmpOldCardNo { get; set; }
        public string StrEmpOwnLanguageID { get; set; }
        public string StrEmpName { get; set; }
        public string StrEmpNameOwnLanguage { get; set; }
        public Nullable<int> intGender { get; set; }
        public Nullable<bool> bitSystemUser { get; set; }
        public Nullable<System.Guid> GReligionID { get; set; }
        public Nullable<int> intMaritalStatus { get; set; }
        public System.DateTime dtBirthDate { get; set; }
        public System.DateTime dtJoiningDate { get; set; }
        public string StrFatherName { get; set; }
        public string StrMotherName { get; set; }
        public string StrCurrentAddress { get; set; }
        public string StrCurrAddrVillageMohalla { get; set; }
        public string StrCurrAddrPostOfficeName { get; set; }
        public string StrCurrAddrPostCode { get; set; }
        public Nullable<System.Guid> GCurrAddrAreaInfoID { get; set; }
        public Nullable<System.Guid> GCurrAddrThanaUpazilaInfoID { get; set; }
        public Nullable<System.Guid> GCurrAddrDistrictInfoID { get; set; }
        public string StrPermanentAddress { get; set; }
        public string StrPerAddrVillageMohalla { get; set; }
        public string StrPerAddrPostofficeName { get; set; }
        public string StrPerAddrPostCode { get; set; }
        public Nullable<System.Guid> GPerAddrAreaInfoID { get; set; }
        public Nullable<System.Guid> GPerAddrThanaUpazilaInfoID { get; set; }
        public Nullable<System.Guid> GPerAddrDistrictInfoID { get; set; }
        public string StrEmpPssportNo { get; set; }
        public string StrEmpNationalID { get; set; }
        public string strEmpMobileNo { get; set; }
        public Nullable<decimal> numEmpWeightKG { get; set; }
        public string StrEmpIdenMark { get; set; }
        public Nullable<int> intLatePresentPunishmentFlag { get; set; }
        public Nullable<System.Guid> GCreatedBy { get; set; }
        public Nullable<System.DateTime> DtCreatedOn { get; set; }
        public Nullable<System.Guid> GUpdatedBy { get; set; }
        public Nullable<System.DateTime> DtUpdatedOn { get; set; }
        public string strEmailAdress { get; set; }
        public Nullable<System.DateTime> DtConfirmationDate { get; set; }
        public Nullable<System.DateTime> DtResignRetireTerminationDate { get; set; }
        public string strGrade { get; set; }
        public string strShift { get; set; }
        public Nullable<bool> chkEligibleForOverTime { get; set; }
        public string strAlternatePhone { get; set; }
        public string strTIN { get; set; }
        public string strNationalIDCard { get; set; }
        public string strAgeString { get; set; }
        public string strFunctionalDesignation { get; set; }
        public string strBloodGroup { get; set; }
        public Nullable<System.Guid> GNationalityID { get; set; }
        public Nullable<bool> bitCarryForwardProcessForDataUpdate { get; set; }
        public Nullable<bool> bitHeadOffice { get; set; }
        public Nullable<bool> bitIsRoaster { get; set; }
        public Nullable<bool> bitEligibleForVistaGLAccount { get; set; }
        public Nullable<int> intActiveStatus { get; set; }
        public Nullable<System.Guid> DivisionID { get; set; }
        public string FingerPrintNo { get; set; }
        public string RelationWithAlternatePhoneOwner { get; set; }
        public Nullable<byte> ShiftID { get; set; }
        public Nullable<System.Guid> RosterGroupID { get; set; }
        public Nullable<System.Guid> GPaymentRuleSetupID { get; set; }
    }
}
