//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class POST
    {
        public POST()
        {
            this.ADMISSIONINFOes = new HashSet<ADMISSIONINFO>();
            this.ADMISSIONINFOes1 = new HashSet<ADMISSIONINFO>();
            this.ADMISSIONINFOes2 = new HashSet<ADMISSIONINFO>();
        }
    
        public int Id { get; set; }
        public string PostName { get; set; }
        public Nullable<int> ThanaId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public string PostCode { get; set; }
        public string BanglaPostName { get; set; }
    
        public virtual ICollection<ADMISSIONINFO> ADMISSIONINFOes { get; set; }
        public virtual ICollection<ADMISSIONINFO> ADMISSIONINFOes1 { get; set; }
        public virtual ICollection<ADMISSIONINFO> ADMISSIONINFOes2 { get; set; }
        public virtual DISTRICT DISTRICT { get; set; }
        public virtual THANA THANA { get; set; }
    }
}
