//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEMESTER
    {
        public SEMESTER()
        {
            this.ADMISSIONINFOes = new HashSet<ADMISSIONINFO>();
            this.COURSEs = new HashSet<COURSE>();
            this.COURSE_ASSIGN_TO_STUDENT = new HashSet<COURSE_ASSIGN_TO_STUDENT>();
            this.CREATE_ROUTINE = new HashSet<CREATE_ROUTINE>();
            this.FEESSETUPs = new HashSet<FEESSETUP>();
            this.ROUTINEGROUPs = new HashSet<ROUTINEGROUP>();
            this.STUDENT_ATTENDENCE = new HashSet<STUDENT_ATTENDENCE>();
            this.STUDENT_CURRENT_SEMESTER_STATUS = new HashSet<STUDENT_CURRENT_SEMESTER_STATUS>();
            this.STUDENT_RESULT = new HashSet<STUDENT_RESULT>();
            this.STUDENTFEESCOLLECTIONs = new HashSet<STUDENTFEESCOLLECTION>();
        }
    
        public int Id { get; set; }
        public string SemesterNo { get; set; }
        public string BanglaSemesterNo { get; set; }
    
        public virtual ICollection<ADMISSIONINFO> ADMISSIONINFOes { get; set; }
        public virtual ICollection<COURSE> COURSEs { get; set; }
        public virtual ICollection<COURSE_ASSIGN_TO_STUDENT> COURSE_ASSIGN_TO_STUDENT { get; set; }
        public virtual ICollection<CREATE_ROUTINE> CREATE_ROUTINE { get; set; }
        public virtual ICollection<FEESSETUP> FEESSETUPs { get; set; }
        public virtual ICollection<ROUTINEGROUP> ROUTINEGROUPs { get; set; }
        public virtual ICollection<STUDENT_ATTENDENCE> STUDENT_ATTENDENCE { get; set; }
        public virtual ICollection<STUDENT_CURRENT_SEMESTER_STATUS> STUDENT_CURRENT_SEMESTER_STATUS { get; set; }
        public virtual ICollection<STUDENT_RESULT> STUDENT_RESULT { get; set; }
        public virtual ICollection<STUDENTFEESCOLLECTION> STUDENTFEESCOLLECTIONs { get; set; }
    }
}
