//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPI_PROGRAM
    {
        public SIPI_PROGRAM()
        {
            this.ADMISSIONINFOes = new HashSet<ADMISSIONINFO>();
            this.BOOKS_DETAILS = new HashSet<BOOKS_DETAILS>();
            this.COURSEs = new HashSet<COURSE>();
            this.CREATE_ROUTINE = new HashSet<CREATE_ROUTINE>();
            this.SIPI_DEPARTMENT = new HashSet<SIPI_DEPARTMENT>();
        }
    
        public int Id { get; set; }
        public string SIPI_ProgramName { get; set; }
        public string SIPI_ProgramTime { get; set; }
        public string BanglaSIPI_Program { get; set; }
    
        public virtual ICollection<ADMISSIONINFO> ADMISSIONINFOes { get; set; }
        public virtual ICollection<BOOKS_DETAILS> BOOKS_DETAILS { get; set; }
        public virtual ICollection<COURSE> COURSEs { get; set; }
        public virtual ICollection<CREATE_ROUTINE> CREATE_ROUTINE { get; set; }
        public virtual ICollection<SIPI_DEPARTMENT> SIPI_DEPARTMENT { get; set; }
    }
}
