//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPI_DEPARTMENT
    {
        public SIPI_DEPARTMENT()
        {
            this.ADMISSIONINFOes = new HashSet<ADMISSIONINFO>();
            this.BOOKS_DETAILS = new HashSet<BOOKS_DETAILS>();
            this.COURSEs = new HashSet<COURSE>();
            this.COURSE_ASSIGN_TO_STUDENT = new HashSet<COURSE_ASSIGN_TO_STUDENT>();
            this.CREATE_ROUTINE = new HashSet<CREATE_ROUTINE>();
            this.FEESSETUPs = new HashSet<FEESSETUP>();
            this.STUDENT_ATTENDENCE = new HashSet<STUDENT_ATTENDENCE>();
            this.STUDENT_RESULT = new HashSet<STUDENT_RESULT>();
            this.TEACHERs = new HashSet<TEACHER>();
        }
    
        public int Id { get; set; }
        public Nullable<int> SIPI_ProgramId { get; set; }
        public string SIPI_DepartmentName { get; set; }
        public string SIPI_DepartmentCode { get; set; }
        public string BanglaSIPI_Department { get; set; }
        public string SIPI_DepartmentRegulation { get; set; }
        public Nullable<System.DateTime> SIPI_DepartmentEntryDate { get; set; }
    
        public virtual ICollection<ADMISSIONINFO> ADMISSIONINFOes { get; set; }
        public virtual ICollection<BOOKS_DETAILS> BOOKS_DETAILS { get; set; }
        public virtual ICollection<COURSE> COURSEs { get; set; }
        public virtual ICollection<COURSE_ASSIGN_TO_STUDENT> COURSE_ASSIGN_TO_STUDENT { get; set; }
        public virtual ICollection<CREATE_ROUTINE> CREATE_ROUTINE { get; set; }
        public virtual ICollection<FEESSETUP> FEESSETUPs { get; set; }
        public virtual SIPI_PROGRAM SIPI_PROGRAM { get; set; }
        public virtual ICollection<STUDENT_ATTENDENCE> STUDENT_ATTENDENCE { get; set; }
        public virtual ICollection<STUDENT_RESULT> STUDENT_RESULT { get; set; }
        public virtual ICollection<TEACHER> TEACHERs { get; set; }
    }
}
