//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_CURRENT_SEMESTER_STATUS
    {
        public int Id { get; set; }
        public Nullable<int> StudentPKId { get; set; }
        public Nullable<int> CurrentSemesterId { get; set; }
    
        public virtual SEMESTER SEMESTER { get; set; }
    }
}
