//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_ATTENDENCE
    {
        public int ID { get; set; }
        public int StudentPKId { get; set; }
        public int DepartmentId { get; set; }
        public int CampusId { get; set; }
        public int SemesterId { get; set; }
        public Nullable<int> Year { get; set; }
        public System.DateTime Date { get; set; }
        public string Status { get; set; }
    
        public virtual ADMISSIONINFO ADMISSIONINFO { get; set; }
        public virtual CAMPUSINFO CAMPUSINFO { get; set; }
        public virtual SEMESTER SEMESTER { get; set; }
        public virtual SIPI_DEPARTMENT SIPI_DEPARTMENT { get; set; }
    }
}
