//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCfgCommonType
    {
        public System.Guid GCfgCommonTypeID { get; set; }
        public int intSLNo { get; set; }
        public string strModuleName { get; set; }
        public string strType { get; set; }
    }
}
