//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCfgCommon
    {
        public System.Guid GCfgCommonID { get; set; }
        public System.Guid GCfgCommonTypeID { get; set; }
        public int intSlNo { get; set; }
        public string StrName { get; set; }
        public string StrDescription { get; set; }
        public int IntIncrementalPK { get; set; }
    }
}
