//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFactory
    {
        public System.Guid GFactoryID { get; set; }
        public Nullable<byte> intFactoryID { get; set; }
        public System.Guid GCommonIDFactoryType { get; set; }
        public string StrFactoryName { get; set; }
        public string StrFactoryShortName { get; set; }
        public string StrAddress { get; set; }
        public string StrDistrict { get; set; }
        public string StrCountry { get; set; }
        public string StrTelephone { get; set; }
        public string StrEmail { get; set; }
        public string StrFax { get; set; }
        public string StrRemark { get; set; }
        public bool BitStatus { get; set; }
        public byte[] SealWithSignature { get; set; }
        public string GCreatedBy { get; set; }
        public System.DateTime DtCreatedOn { get; set; }
        public string GUpdatedBy { get; set; }
        public System.DateTime DtUpdatedOn { get; set; }
        public string FactoryNameOwnLanguage { get; set; }
        public string FactoryAddressOwnLanguage { get; set; }
    }
}
