//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEACHER
    {
        public TEACHER()
        {
            this.CREATE_ROUTINE = new HashSet<CREATE_ROUTINE>();
            this.CREATE_ROUTINE1 = new HashSet<CREATE_ROUTINE>();
            this.CREATE_ROUTINE2 = new HashSet<CREATE_ROUTINE>();
            this.CREATE_ROUTINE3 = new HashSet<CREATE_ROUTINE>();
            this.CREATE_ROUTINE4 = new HashSet<CREATE_ROUTINE>();
            this.CREATE_ROUTINE5 = new HashSet<CREATE_ROUTINE>();
            this.CREATE_ROUTINE6 = new HashSet<CREATE_ROUTINE>();
            this.CREATE_ROUTINE7 = new HashSet<CREATE_ROUTINE>();
        }
    
        public int Id { get; set; }
        public string TeacherName { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> CampusId { get; set; }
    
        public virtual CAMPUSINFO CAMPUSINFO { get; set; }
        public virtual ICollection<CREATE_ROUTINE> CREATE_ROUTINE { get; set; }
        public virtual ICollection<CREATE_ROUTINE> CREATE_ROUTINE1 { get; set; }
        public virtual ICollection<CREATE_ROUTINE> CREATE_ROUTINE2 { get; set; }
        public virtual ICollection<CREATE_ROUTINE> CREATE_ROUTINE3 { get; set; }
        public virtual ICollection<CREATE_ROUTINE> CREATE_ROUTINE4 { get; set; }
        public virtual ICollection<CREATE_ROUTINE> CREATE_ROUTINE5 { get; set; }
        public virtual ICollection<CREATE_ROUTINE> CREATE_ROUTINE6 { get; set; }
        public virtual ICollection<CREATE_ROUTINE> CREATE_ROUTINE7 { get; set; }
        public virtual SIPI_DEPARTMENT SIPI_DEPARTMENT { get; set; }
    }
}
